# This is the Docker Compose for setting up a local dev environment.
version: '3.8'

services:
    worker:
        image: node:14
        volumes:
            - '.:/src'
        ports:
            - 6609:6609
        working_dir: /src
        command: yarn worker

    ui:
        image: node:14
        volumes:
            - '.:/src'
        ports:
            - 6601:6601
        working_dir: /src
        command: yarn ui
