// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// ChallengesColumns holds the columns for the "challenges" table.
	ChallengesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "challenge_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "user_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "human", Type: field.TypeString, Unique: true},
		{Name: "magic", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// ChallengesTable holds the schema information for the "challenges" table.
	ChallengesTable = &schema.Table{
		Name:        "challenges",
		Columns:     ChallengesColumns,
		PrimaryKey:  []*schema.Column{ChallengesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// GuildsColumns holds the columns for the "guilds" table.
	GuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "snowflake", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "message", Type: field.TypeString, Size: 2147483647},
		{Name: "categories", Type: field.TypeJSON},
		{Name: "entitlements", Type: field.TypeJSON},
	}
	// GuildsTable holds the schema information for the "guilds" table.
	GuildsTable = &schema.Table{
		Name:        "guilds",
		Columns:     GuildsColumns,
		PrimaryKey:  []*schema.Column{GuildsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "session_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "user_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"oauth", "dm"}},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:        "sessions",
		Columns:     SessionsColumns,
		PrimaryKey:  []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChallengesTable,
		GuildsTable,
		SessionsTable,
	}
)

func init() {
}
