name: Roleypoly CI

on:
  push:
  pull_request:

jobs:
  node_test:
    runs-on: ubuntu-latest
    name: Node CI
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '20'
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn lint

      # - run: yarn test

  worker_build:
    runs-on: ubuntu-latest
    name: Worker Build & Publish
    if: startsWith(github.ref, 'refs/heads/dependabot/') != true
    needs:
      - node_test
    strategy:
      matrix:
        worker:
          - api
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '20'
          cache: yarn

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_TF_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCS_PROJECT_ID }}
          export_default_credentials: true

      - name: Check if already deployed
        id: check
        run: |
          gsutil stat gs://roleypoly-artifacts/workers/${{ github.sha }}/index.mjs \
            && echo ::set-output name=skip::1 \
            || echo ::set-output name=skip::0

      - run: yarn install --frozen-lockfile
        if: steps.check.outputs.skip == '0'

      - run: |
          yarn build:api
        if: steps.check.outputs.skip == '0'

      - id: upload-file
        if: github.event_name == 'push' && steps.check.outputs.skip == '0'
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: packages/api/dist/index.mjs
          destination: roleypoly-artifacts/workers/${{ github.sha }}

  docker_build:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/dependabot/') != true
    needs:
      - node_test
    strategy:
      matrix:
        dockerfile:
          - bot
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/roleypoly/${{matrix.dockerfile}}
          tag-sha: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: roleypoly
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker
        with:
          context: ./packages/${{ matrix.dockerfile }}
          file: ./packages/${{ matrix.dockerfile }}/Dockerfile
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Pre-deploy - Save digest.txt
        run: |
          echo "${{ steps.docker.outputs.digest }}" > digest.txt

      - name: Pre-deploy - Make digest artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.dockerfile }}-digest
          path: digest.txt

  trigger_deploy:
    name: Deploy to Stage
    needs:
      - docker_build
      - worker_build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Get Bot digest
        uses: actions/download-artifact@v2
        with:
          name: bot-digest
          path: .digests/bot

      - name: Set digests as addressable
        id: digests
        env:
          IMAGES: bot
        run: |
          echo ::set-output name=bot::@$(cat .digests/bot/digest.txt)

      - name: Invoke Deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.GITOPS_TOKEN }}
          inputs: |-
            {
              "environment": "stage",
              "worker_tag": "${{ github.sha }}",
              "bot_tag": "${{ steps.digests.outputs.bot }}"
            }
